version: "3.8"

services:
  web:
    image: himachen/short-url-system:latest
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "8000:8000"
    # volumes:
    #   - .:/app
    #command: ["gunicorn", "--bind", "0.0.0.0:8000", "shortUrl.wsgi:application"]

  db:
    image: postgres:14
    container_name: postgres_db_test3
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    container_name: redis_test3
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: